name = "TrueRandom"
uuid = "e77d87cc-b440-4d37-a0c9-dafffb38ae8a"
authors = ["TEC <tec@tecosaur.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
